name: Daily Auctions Data

on:
    push:
    schedule:
        - cron: '* * * * *'

env:
    TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
    TELEGRAM_CHANNEL_ID: ${{secrets.TELEGRAM_CHANNEL_ID}}

jobs:
    Daily-Run-Auctions-Data:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Run App
              run: python auctions_data.py
