name: Daily Auctions Data

on:
    workflow_dispatch:

env:
    TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
    TELEGRAM_CHANNEL_ID: ${{secrets.TELEGRAM_CHANNEL_ID}}

jobs:
    Daily-Run-Auctions-Data:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.11.5'
        
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install pandas
                python -m pip install requests
                python -m pip install openpyxl
            - name: Run App
              run: python auctions_data.py
