name: Daily Auctions Data

on:
    push:
    schedule:
        - cron: '* * * * *'

env:
    TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
    TELEGRAM_CHANNEL_ID: ${{secrets.TELEGRAM_CHANNEL_ID}}

jobs:
    Daily-Run-Auctions-Data:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.11.5'
        
            - name: Install dependencies
              run: |
                python -m pip install 
                pip install pandas
                pip install requests
            - name: Run App
              run: python auctions_data.py
